language: go

go:
- 1.16.x

before_scripts:

scripts:
- go test -v ./...

before_deploy:
- touch .env
- echo HOST=$HOST >> .env
- echo PORT=$PORT >> .env
- echo DEBUG=$DEBUG >> .env
- echo MONGO_DB_URI=$MONGO_DB_URI >> .env
- echo MONGO_DB_NAME=$MONGO_DB_NAME >> .env
- echo JWT_SECRET_KEY=$JWT_SECRET_KEY >> .env
- echo GOOGLE_OAUTH_CLIENT_ID=$GOOGLE_OAUTH_CLIENT_ID >> .env
- echo SENTRY_DSN=$SENTRY_DSN >> .env

deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: WDTdNXzMU7FDy1YvoHF6RguoGkOfND0RpCxeN/2a3hE6TZhDwnZhhOWOXb2y28cOw26zZVtPhty98TVxnOBW5HcMuFuErVS3pcc/G2LNy6RPCRCveCAqxMOmY1UFIVAhnK43FzxooURCEYXOjJ2s2R7aV51FP1gLUhmYutQpOMo6veEkZs56qZVn/1K4K5rtct09BO09LxyI/jDZTQK0q95LTXcYrpTT6bmbU+O/bVKQWaUsxR89wWxqUCqdpmSXLFRIQETDUOdLTUEp660MQGAoTZrERyB7u8Cy1KqfhDetLTElfb1i92vKvhALVLuj00UneePgTv1c7OiQFfCZ8/gAYdOlG/nrxkVisje4v7Aypni9eWcAcLQ1f0sepbUTBtbdJ/i1rE6yjyKH5Z/Dv5A22DUss55DCN+0KXO0btzw3mdBRS3yx8BlGufdbPauV5Z4pwHmE2N6HOh4Emo5gUJVX0eYzjgbSTXF861jLXxPnm1EmEO49FnsmQbLDEl2FOaaMYBgWJzPZtwm2/oWxLk5IliATcVGJteYOL+H+71n6o1DDTALaSinhPZEt/ZI0QxKjp/uivtf1tTJGbJAKq2l4OjV4T/CVr7CZ4RCPb3rW0ia0XG2BKwwBvZCruVBvJh8HWOeH0XzONhKzir7uzN5wo9nnq2qhwgnyoMisLg=
  on: main
  app:
    main: ardafirdausr-todo-server
